#!/bin/bash

cd bin

rm -f *.log

echo "Starting UserServer"
start_aterm -e screen -S server -t UserServer mono --debug OpenSim.Grid.UserServer.exe &
sleep 5

echo "Starting GridServer"
screen -S server -X screen -t GridServer mono --debug OpenSim.Grid.GridServer.exe
sleep 5

echo "Starting AssetServer"
screen -S server -X screen -t AssetServer mono --debug OpenSim.Grid.AssetServer.exe
sleep 5

echo "Starting InventoryServer"
screen -S server -X screen -t InventoryServer mono --debug OpenSim.Grid.InventoryServer.exe
sleep 5

echo "Starting MessagingServer"
screen -S server -X screen -t MessagingServer mono --debug OpenSim.Grid.MessagingServer.exe

